apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-service-secret
  namespace: production
spec:
  encryptedData:
    api_key: AgDMJ29i4tsJD5Rire7fUSnidFCVB4MCmkvFhron5ikamARu69SLwr2/DT2ReReeKVQG5BYCWp0u1GXdw1nwDY3y/u4/ewR8/ShckWPWOTwnbxxmUCI97zXCRkOSjhxgp0cLDPqaHVtGbqxCwE+Ty7BwIe/7TNKpqoDzAaiDzQdieHD2KHPo7h/6IXdsmSi6aZACg0MArHVAKu9iwXjVYEz7Awb8Q8gegN0L+r+RnwQsl1ituqYI86bsndp6Swe4AnPhegDjrcjFEinBgzrh1rJFtxpYTFtRKxouiuXWuBzOEnKXM8NZPAPtkLccEn48P2lrBLWA1HIucKRe8ysAZ+5PFQmRQWPt/RZxrmADpQY4+gbt0k7ErP9/VAyczv2rXs0bAP5VTMVAnQYL5Fr6MuqxVBYC57YIlqX0eOetRRNX1Ororjbeuv6pjY9meO0oN5xsdeqJPBn9J+UXJ7aw+HQCGklE7T8UqHL4qJPsZX6BhVCuUZjYhAJp+U9bVAoXEyr9pzOBIV6R/B0dJ2rSOdcIEpPUhA9sxqFKYE4su8Q6Xp1bJ9zopcxtC0N3Pw7PL4bNj8LvKBPI6BC9ktucQTKucCKLOb0b4exV+wU5emuey86FMfnmL3mpU23MrYYFX6l1NpM5n5LpjgHUDACHPXkA0f+hMhBb/4DIr8OLPPSQNXblGO9sNey/U5Qzey7TElrnzHbonzch8va2CA==
    db_password: AgBiPqKH+DribLnjv5OdCUFUHQpzE972+9Eh9Ttm6nJUlVeV0iuUeB77cNoah1Su8WxtorM8Pud3oqEkREViJMIigpTyCt59qltMSTA/0KFPP48F4JK9Y2DMozqg46sv3p5i1LxXSznUN+hVwf9FVtDDDiBza0DpUCJLHjOk3TV4v87SsELUZpMqpP4VssmROt3gMaw6wTs2pfClyC2YSBw8C9JxEFaSxWsVTQ5zY3lYBzIm1+qXSQ4c96p+fG/WhYI3VX8EEPEArDfvjgK60ruMXJvfEtO73duZQiRK9w2czEgD3M8UjOzr6I/EEhN1pnNwYJSFmvCNE9s/GJvGAP7kECt+gZoQsUvoKlV2WAarc/uKfhLFBsXd5Sx1waEaOlVF/jgbxVP87dY0QDK4TMrNs+16R6mOcqEA+LXp6Cu6VjfdaUFythEcvT5qwN/mv7yeHIi304fe3jiE2bw8h2202O5NHRc1/sKOYEbTtMte/J6vjMzinap0dXMkpTW5jShp8UkIwqQGD7sR/u7/pw0jwK29kcWt0LtxJOFjxuDN87P0WeLtw18voRmLOdppnM4UZ1mwX0jFvwJxSGhXVlj9iobr8KQU6c6MpnndjsorTtGSwCW81AY8lo8islePb8UpDkGLOw04SnCg+UGzDr0sK7Zs6QzeI9jo/MKEgpsTcQGBqJZtH2ULDdYwySUa6pe8naoGL5mype3Dyblqmw==
  template:
    metadata:
      creationTimestamp: null
      name: api-service-secret
      namespace: production
---
